sudo: false
language: java
jdk:
  - oraclejdk8
services:
- docker
cache:
  directories:
  - "$HOME/.cache"
deploy:
  provider: script
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn -f java18-test-features deploy"
  skip_cleanup: true
  on:
    tags: true

notifications:
  email:
    recipients:
    - discosremember@gmail.com
    on_success: change
    on_failure: always
